import React, { useState, useRef } from 'react';
import { ConsultationResponse } from '../../types/oracle';

interface ShareDialogProps {
  isOpen: boolean;
  onClose: () => void;
  response: ConsultationResponse | null;
}

const ShareDialog: React.FC<ShareDialogProps> = ({ isOpen, onClose, response }) => {
  const [currentIndex, setCurrentIndex] = useState(0);
  const cardRef = useRef<HTMLDivElement>(null);

  if (!isOpen || !response || !response.shareableOptions || response.shareableOptions.length === 0) {
    return null;
  }

  const options = response.shareableOptions;
  const currentOption = options[currentIndex];

  const nextOption = () => {
    setCurrentIndex((prev) => (prev + 1) % options.length);
  };

  const prevOption = () => {
    setCurrentIndex((prev) => (prev - 1 + options.length) % options.length);
  };

  const goToOption = (index: number) => {
    setCurrentIndex(index);
  };

  const truncateQuery = (query: string, maxLength: number = 80): string | null => {
    if (query.length <= maxLength) {
      return query;
    }
    return null; // Skip if too long
  };



  const normalizeTitle = (title: string): string => {
    // Apply the same normalization logic as the scripts
    if (title.startsWith("Orpheus to") || title.startsWith("Hymn to")) {
      return title;
    }
    
    if (title.startsWith("Of ")) {
      return title.replace("Of ", "To ").replace(/\.$/, '');
    }
    
    if (!title.startsWith("To ") && !title.startsWith("Hymn")) {
      return `To ${title}`;
    }
    
    return title;
  };

  const getCorpusDisplayName = (corpus: string): string => {
    const corpusMap: Record<string, string> = {
      'hymns': 'Orphic Hymns',
      'argonautica': 'Orphic Argonautica', 
      'lithica': 'Orphic Lithica'
    };
    return corpusMap[corpus] || corpus;
  };

  const copyToClipboard = async () => {
    if (!cardRef.current) return;
    
    try {
      // For now, copy the text content. Later we'll add image generation
      const cardText = generateCardText();
      await navigator.clipboard.writeText(cardText);
      
      // Could add a toast notification here
      console.log('✅ Card text copied to clipboard');
    } catch (error) {
      console.error('Failed to copy to clipboard:', error);
    }
  };

  const generateCardText = (): string => {
    const truncatedQuery = truncateQuery(response.query);
    const normalizedTitle = normalizeTitle(currentOption.content.sectionTitle);
    const corpusName = getCorpusDisplayName(currentOption.corpus);
    const incense = currentOption.metadata?.incense?.english;
    const timestamp = new Date(response.timestamp).toLocaleDateString();
    
    let cardText = '';
    
    if (truncatedQuery) {
      cardText += `"${truncatedQuery}"\n\n`;
    }
    
    cardText += `${normalizedTitle}\n`;
    cardText += `${corpusName}\n`;
    
    if (incense) {
      cardText += `${incense}\n`;
    }
    
    cardText += `\n${timestamp}\n\n`;
    cardText += `"${currentOption.content.text}"\n\n`;
    cardText += `Generated by Cleros Oracle`;
    
    return cardText;
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-gray-900 p-6 rounded-lg max-w-2xl w-full mx-4 max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="flex justify-between items-center mb-6">
          <h2 className="text-xl font-bold text-white">Share Oracle Card</h2>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-white text-2xl"
          >
            ×
          </button>
        </div>

        {/* Carousel Controls */}
        <div className="flex items-center justify-between mb-4">
          <button
            onClick={prevOption}
            disabled={options.length <= 1}
            className="px-3 py-1 bg-purple-600 text-white rounded disabled:opacity-50 disabled:cursor-not-allowed hover:bg-purple-700"
          >
            ← Previous
          </button>
          
          <div className="flex items-center space-x-2">
            {options.map((_, index) => (
              <button
                key={index}
                onClick={() => goToOption(index)}
                className={`w-3 h-3 rounded-full transition-colors ${
                  index === currentIndex ? 'bg-purple-500' : 'bg-gray-600'
                }`}
              />
            ))}
          </div>
          
          <button
            onClick={nextOption}
            disabled={options.length <= 1}
            className="px-3 py-1 bg-purple-600 text-white rounded disabled:opacity-50 disabled:cursor-not-allowed hover:bg-purple-700"
          >
            Next →
          </button>
        </div>

        {/* Option Info */}
        <div className="text-sm text-gray-400 mb-4 text-center">
          Option {currentIndex + 1} of {options.length} • {currentOption.type} • 
          {currentOption.type === 'sentence' && currentOption.content.lineCount && 
            ` ${currentOption.content.lineCount} line${currentOption.content.lineCount !== 1 ? 's' : ''}`
          }
        </div>

        {/* Card Preview */}
        <div 
          ref={cardRef}
          className="bg-white text-black p-6 rounded-lg shadow-lg mb-6 min-h-[300px]"
        >
          {/* Query (if short enough) */}
          {truncateQuery(response.query) && (
            <div className="text-center mb-6">
              <p className="text-sm italic text-gray-600">&ldquo;{truncateQuery(response.query)}&rdquo;</p>
            </div>
          )}

          {/* Source Attribution */}
          <div className="text-center mb-4">
            <h3 className="text-lg font-bold text-gray-800">
              {normalizeTitle(currentOption.content.sectionTitle)}
            </h3>
            <p className="text-sm text-gray-600">{getCorpusDisplayName(currentOption.corpus)}</p>
            {currentOption.metadata?.incense?.english && (
              <p className="text-sm text-gray-500 italic">
                {currentOption.metadata.incense.english}
              </p>
            )}
          </div>

          {/* Timestamp */}
          <div className="text-center text-xs text-gray-400 mb-6">
            {new Date(response.timestamp).toLocaleDateString()}
          </div>

          {/* Main Quote */}
          <div className="text-center">
            <blockquote className="text-base leading-relaxed text-gray-800 italic">
&ldquo;{currentOption.content.text}&rdquo;
            </blockquote>
          </div>

          {/* Footer placeholder for QR code and branding */}
          <div className="mt-6 flex justify-between items-center text-xs text-gray-400">
            <span>Generated by Cleros Oracle</span>
            <div className="w-8 h-8 border border-gray-300 flex items-center justify-center">
              QR
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex space-x-3">
          <button
            onClick={copyToClipboard}
            className="flex-1 px-4 py-2 bg-purple-600 text-white rounded hover:bg-purple-700 transition-colors"
          >
            📋 Copy Text
          </button>
          <button
            onClick={() => {/* TODO: Save as image */}}
            className="flex-1 px-4 py-2 bg-green-600 text-white rounded hover:bg-green-700 transition-colors"
          >
            💾 Save Image
          </button>
          <button
            onClick={onClose}
            className="px-4 py-2 bg-gray-600 text-white rounded hover:bg-gray-700 transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};

export default ShareDialog;
