name: Build and Deploy

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SORTES repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd web
          npm install

      - name: Build
        run: |
          cd web
          CI=false SKIP_PREFLIGHT_CHECK=true DISABLE_ESLINT_PLUGIN=true npm run build

      - name: Checkout main repository
        uses: actions/checkout@v3
        with:
          repository: neumanns-workshop/neumanns-workshop.github.io
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: main-repo

      - name: Copy build files to main repository
        run: |
          # Make sortes-app directory and copy build files there (keeping existing structure)
          mkdir -p main-repo/sortes-app
          cp -R web/build/* main-repo/sortes-app/
          
          # Create sortes directory with redirect to sortes-app
          mkdir -p main-repo/sortes
          cat > main-repo/sortes/index.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
            <meta http-equiv="refresh" content="0; url=/sortes-app/" />
            <title>Redirecting to SORTES</title>
          </head>
          <body>
            <p>Redirecting to SORTES application...</p>
            <p><a href="/sortes-app/">Click here if you are not redirected automatically</a></p>
          </body>
          </html>
          EOL
          
          # Ensure .nojekyll exists to prevent Jekyll processing
          touch main-repo/.nojekyll
          
          # List directories to verify structure
          echo "Directory structure:"
          ls -la main-repo/
          ls -la main-repo/sortes/
          ls -la main-repo/sortes-app/

      - name: Configure Git
        run: |
          cd main-repo
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Commit and push changes to main repository
        run: |
          cd main-repo
          git add sortes sortes-app .nojekyll
          git commit -m "Update SORTES app and add redirect (triggered by ${{ github.event.head_commit.message }})" || echo "No changes to commit"
          git push 