name: Build and Deploy

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SORTES repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd web
          npm ci

      - name: Build
        run: |
          cd web
          npm run build

      - name: Checkout main repository
        uses: actions/checkout@v3
        with:
          repository: neumanns-workshop/neumanns-workshop.github.io
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: main-repo

      - name: Copy build files to main repository
        run: |
          mkdir -p main-repo/sortes-app
          cp -R web/build/* main-repo/sortes-app/

      - name: Configure Git
        run: |
          cd main-repo
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Commit and push changes to main repository
        run: |
          cd main-repo
          git add sortes-app
          git commit -m "Update SORTES app (triggered by ${{ github.event.head_commit.message }})" || echo "No changes to commit"
          git push 